/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('./flightHelmet/FlightHelmet.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow geometry={nodes.Hose_low.geometry} material={materials.HoseMat} />
      <mesh castShadow geometry={nodes.RubberWood_low.geometry} material={materials.RubberWoodMat} />
      <mesh castShadow geometry={nodes.GlassPlastic_low.geometry} material={materials.GlassPlasticMat} />
      <mesh castShadow geometry={nodes.MetalParts_low.geometry} material={materials.MetalPartsMat} />
      <mesh castShadow geometry={nodes.LeatherParts_low.geometry} material={materials.LeatherPartsMat} />
      <mesh castShadow geometry={nodes.Lenses_low.geometry} material={materials.LensesMat} />
    </group>
  )
}

useGLTF.preload('./flightHelmet/FlightHelmet.gltf')
