/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('fox/Fox.gltf')
  const { actions } = useAnimations(animations, group)
  console.log({actions, animations});

  /**
   * useful link for animation actions (AnimationAction) ⬇️
   * https://drei.pmnd.rs/?path=/story/abstractions-useanimations--use-animations-st
   */
  function animateFox() {
    /**
     * Actions: Walk, Run, Survey
     */
    // actions.Survey.play()
    actions.Survey.play().fadeIn(1)
    setTimeout(() => {
      // actions.Survey.reset()
      actions.Survey.fadeOut(1) // works
    }, 5000);
  }
  return (
    <group ref={group} {...props} dispose={null} onClick={animateFox}>
      <group scale={[0.025, 0.025, 0.025]}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh castShadow geometry={nodes.fox.geometry} material={materials.fox_material} skeleton={nodes.fox.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('fox/Fox.gltf')
